# Expose port 8080
# Visit `:8080/stub_status` to see Nginx server statistics.
# @See `.ddev/nginx_full/stub_status.conf`
web_extra_exposed_ports:
  - name: webserver
    container_port: 8080
    http_port: 8081
    https_port: 8080
